spring.application.name=auth-service
spring.profiles.active=dev

server.port=${AUTH_SERVICE_PORT}

spring.datasource.url=${AUTH_DB_URL}
spring.datasource.username=${AUTH_DB_USERNAME}
spring.datasource.password=${AUTH_DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME}

jwt.secret=${JWT_SECRET}

spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.database=${REDIS_DATABASE}

# Optional: Hibernate & JPA
spring.jpa.database-platform=${JPA_DATABASE_PLATFORM}
spring.jpa.show-sql=${JPA_SHOW_SQL}
# Hibernate DDL auto generation
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}

#for scheduling
spring.main.allow-bean-definition-overriding=${ALLOW_BEAN_DEFINITION_OVERRIDING}

logging.level.root=${LOGGING_LEVEL_ROOT}
