spring.application.name=notification-service
spring.profiles.active=dev
server.port=${NOTIFICATION_SERVICE_PORT}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}

carwash.events.exchange=${CARWASH_EVENTS_EXCHANGE}
carwash.events.notification-queue=${NOTIFICATION_EMAIL_QUEUE}
notification.mail.from=${NOTIFICATION_MAIL_FROM}

logging.level.root=${LOGGING_LEVEL_ROOT}
