spring.application.name=profile-service
spring.profiles.active=dev

server.port=${CUSTOMER_SERVICE_PORT}

spring.datasource.url=${CUSTOMER_DB_URL}
spring.datasource.username=${CUSTOMER_DB_USERNAME}
spring.datasource.password=${CUSTOMER_DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME}

spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}
jwt.secret=${JWT_SECRET}

logging.level.org.springframework.security=${LOGGING_LEVEL_SECURITY}
logging.level.org.springframework.web=${LOGGING_LEVEL_WEB}
logging.level.org.springframework.boot.autoconfigure.security=${LOGGING_LEVEL_SECURITY_AUTOCONFIG}
logging.level.org.springframework.security.oauth2.server.resource=${LOGGING_LEVEL_OAUTH2_RESOURCE}
logging.level.org.springframework.security.oauth2.jwt=${LOGGING_LEVEL_OAUTH2_JWT}
logging.level.org.springframework.security.oauth2.client=${LOGGING_LEVEL_OAUTH2_CLIENT}
logging.level.org.springframework.security.oauth2.server.authorization=${LOGGING_LEVEL_OAUTH2_AUTHORIZATION}
logging.level.org.springframework.security.oauth2.server.authorization.client=${LOGGING_LEVEL_OAUTH2_AUTHORIZATION_CLIENT}
logging.level.org.springframework.security.oauth2.server.authorization.token=${LOGGING_LEVEL_OAUTH2_AUTHORIZATION_TOKEN}
logging.level.org.springframework.security.oauth2.server.authorization.web=${LOGGING_LEVEL_OAUTH2_AUTHORIZATION_WEB}
logging.level.org.springframework.security.oauth2=${LOGGING_LEVEL_OAUTH2}

spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.database=${REDIS_DATABASE}

# Optional: Hibernate & JPA
spring.jpa.database-platform=${JPA_DATABASE_PLATFORM}
spring.jpa.show-sql=${JPA_SHOW_SQL}
# Hibernate DDL auto generation
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}

logging.level.root=${LOGGING_LEVEL_ROOT}

auth.service.url=${AUTH_SERVICE_URL}
