spring.application.name=payment-service
spring.profiles.active=dev
server.port=${PAYMENT_SERVICE_PORT}

spring.datasource.url=${PAYMENT_DB_URL}
spring.datasource.username=${PAYMENT_DB_USERNAME}
spring.datasource.password=${PAYMENT_DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME}

spring.jpa.database-platform=${JPA_DATABASE_PLATFORM}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}

jwt.secret=${JWT_SECRET}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

carwash.events.exchange=${CARWASH_EVENTS_EXCHANGE}

booking.service.base-url=${BOOKING_SERVICE_URL}
carwash.internal.booking-confirmation-token=${BOOKING_CONFIRMATION_TOKEN}

razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_KEY_SECRET}
razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET}

logging.level.root=${LOGGING_LEVEL_ROOT}
